/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic;

import base.Utilisateur;
import javax.swing.JOptionPane;

/**
 *
 * @author marine
 */
public class BeginFrame extends javax.swing.JFrame {

    /**
     * Creates new form BeginFrame
     */
    public BeginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nouvellePartie = new javax.swing.JButton();
        regarderPartie = new javax.swing.JButton();
        boutonClassement = new javax.swing.JButton();
        boutonValiderNom = new javax.swing.JButton();
        saisieNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelConfirmation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nouvellePartie.setText("Nouvelle partie simple");
        nouvellePartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouvellePartieActionPerformed(evt);
            }
        });

        regarderPartie.setText("Recharger une partie simple");
        regarderPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regarderPartieActionPerformed(evt);
            }
        });

        boutonClassement.setText("Afficher le classement");
        boutonClassement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonClassementActionPerformed(evt);
            }
        });

        boutonValiderNom.setText("OK");
        boutonValiderNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderNomActionPerformed(evt);
            }
        });

        saisieNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saisieNomActionPerformed(evt);
            }
        });

        jLabel1.setText("Votre nom");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nouvellePartie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regarderPartie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boutonClassement, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saisieNom, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boutonValiderNom))
                    .addComponent(labelConfirmation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonValiderNom)
                    .addComponent(saisieNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelConfirmation, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(nouvellePartie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regarderPartie)
                .addGap(69, 69, 69)
                .addComponent(boutonClassement)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nouvellePartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouvellePartieActionPerformed
        // TODO add your handling code here:
        // Génération d'une nouvelle partie
        generer_partie_simple(true);
    }//GEN-LAST:event_nouvellePartieActionPerformed

    private void regarderPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regarderPartieActionPerformed
        // TODO add your handling code here:
        // Génération d'une ancienne partie
        generer_partie_simple(false);
    }//GEN-LAST:event_regarderPartieActionPerformed

    private void boutonClassementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonClassementActionPerformed
        // TODO add your handling code here:

        /*
        // Affichage du classement dans la console
        Utilisateur.afficherClassement();
        */
        
        // Affichage du classement dans une nouvelle Fenetre
        new ClassementFrame().setVisible(true);
    }//GEN-LAST:event_boutonClassementActionPerformed

    private void boutonValiderNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderNomActionPerformed
        // TODO add your handling code here:

        // Validation
        validerNomUtilisateur();
    }//GEN-LAST:event_boutonValiderNomActionPerformed

    private void saisieNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saisieNomActionPerformed
        // TODO add your handling code here:

        // Validation
        validerNomUtilisateur();
    }//GEN-LAST:event_saisieNomActionPerformed

    public void generer_partie_simple(boolean nouvellePartie) {
        String nom = saisieNom.getText();
        if (nom.equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez entrer un nom.", "Erreur", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Création de l'utilisateur
            validerNomUtilisateur();
            // Génération des données nécessaires (couleurs, ...)
            Config.init();
            MainFrame mf = new MainFrame();
            if (!nouvellePartie) {
                // Recharge du plateau
                if (!MainFrame.plateau.recharger()) {
                    // Affichage d'un message d'erreur
                    JOptionPane.showMessageDialog(null, "Erreur lors de la recharge\n", "Erreur", JOptionPane.ERROR_MESSAGE);
                } else {
                    this.dispose();
                    mf.addKeyListener(mf.controleur);
                    mf.setVisible(true);
                }
            } else {
                this.dispose();
                mf.addKeyListener(mf.controleur);
                mf.setVisible(true);
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonClassement;
    private javax.swing.JButton boutonValiderNom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelConfirmation;
    private javax.swing.JButton nouvellePartie;
    private javax.swing.JButton regarderPartie;
    private javax.swing.JTextField saisieNom;
    // End of variables declaration//GEN-END:variables

    /**
     * Méthode qui créer un nouvel utilisateur.
     */
    private void validerNomUtilisateur() {
        // Création de l'utilisateur.
        MainFrame.utilisateur = new Utilisateur(saisieNom.getText());
        // Affichage 
        labelConfirmation.setText("Bonjour " + saisieNom.getText());
    }
}
